server.port=${PORT:8080}
spring.application.name=bfhl-api

# User Configuration
app.user.full-name=aditya_kushwah
app.user.email=adityakushwah241283@acropolis.in
app.user.roll-number=0827IT243D01
app.user.dob=16122004
